"""Tempo, key, mode and singer statistics per style family, from the caption-rewriter cards.

Usage: python3 -I template_stats.py > ../library/genre-stats.md

Reads the family indexes of the music-caption-rewriter skill that
fetch_caption_skill.sh installs. Each card row gives "N BPM; <key> <major|minor>"
and a vocal cue such as "Singer A (Male) and Singer B (Female)".
"""
import re
import statistics
from collections import Counter
from pathlib import Path

INDEXES = (Path(__file__).resolve().parent.parent
           / ".claude/skills/music-caption-rewriter/references")
TEMPO_KEY = re.compile(r"^(\d+) BPM; ([A-G][#b]?) (major|minor)$")


def singers(cue):
    cue = cue.lower()
    if "instrumental" in cue:
        return "instrumental"
    n = len(re.findall(r"singer [a-z]\b", cue)) or 1
    if n > 1:
        return "two or more"
    if "female" in cue:
        return "one female"
    if "male" in cue:
        return "one male"
    return "one, unstated"


def pct(part, whole):
    return f"{100 * part / whole:.0f}%"


rows = []
for path in sorted(INDEXES.glob("index-*.md")):
    family = path.stem.removeprefix("index-")
    bpms, keys, minors, voices, skipped = [], Counter(), 0, Counter(), 0
    for line in path.read_text().splitlines():
        if not line.startswith("| `"):
            continue
        cells = [c.strip() for c in line.split("|")]
        m = TEMPO_KEY.match(cells[4])
        voices[singers(cells[6])] += 1
        if not m:
            skipped += 1
            continue
        bpms.append(int(m[1]))
        keys[f"{m[2]} {m[3]}"] += 1
        minors += m[3] == "minor"
    q = statistics.quantiles(bpms, n=10)
    rows.append((family, len(bpms) + skipped, min(bpms), q[0], statistics.median(bpms), q[-1],
                 max(bpms), pct(minors, len(bpms)), keys.most_common(3), voices))

print("# Genre statistics from the MiniMax caption templates\n")
print("Counts over the 1,000 cards of the `music-caption-rewriter` skill, one row per style family. "
      "BPM columns give the minimum, 10th percentile, median, 90th percentile and maximum. "
      "Generated by `scripts/template_stats.py`.\n")
print("| Family | Cards | BPM min | BPM p10 | BPM median | BPM p90 | BPM max | Minor keys | Top keys |")
print("|---|---|---|---|---|---|---|---|---|")
for fam, n, lo, p10, med, p90, hi, minor, top, _ in rows:
    tops = ", ".join(f"{k} ({c})" for k, c in top)
    print(f"| {fam} | {n} | {lo} | {p10:.0f} | {med:.0f} | {p90:.0f} | {hi} | {minor} | {tops} |")
print("\n## Singers per card\n")
print("| Family | One male | One female | One, unstated | Two or more | Instrumental |")
print("|---|---|---|---|---|---|")
for fam, n, *_, voices in rows:
    cols = ["one male", "one female", "one, unstated", "two or more", "instrumental"]
    print(f"| {fam} | " + " | ".join(pct(voices[c], n) for c in cols) + " |")
